### ISSUE TITLE
How do these read_hook methods in InnerDetoxHook work？

### ISSUE THREAD

**Issue by a101269** [cooperleong00/ToxificationReversal#2]
I would like to ask what the function of innerdetox_hook is. The read_hook in modeling_gpt2-innerdetox  innerdetox_hook.register_hooks(self, innerdetox_hook.read_hook) does not pass any parameters, and the write_hook does not pass any parameters either.How do these two methods work？

**Comment by cooperleong00** [comment]
Hi, the parameters for the read_hook are 
`def read_hook(self, module, input, output, module_name=None, prompt_end_indices=None)`,
where the module, input, and output are passed by the Pytorch's register_forward_hook function (https://pytorch.org/docs/stable/generated/torch.nn.modules.module.register_module_forward_hook.html),

and the  module_name and prompt_end_indices are passed via a partial function at https://github.com/cooperleong00/ToxificationReversal/blob/d46a0fe5e0b95bb2d6df2fa72540d54eb68a4959/scripts/run_generation.py#L107

Likewise, the parameter module_name of the write_hook is passed at
https://github.com/cooperleong00/ToxificationReversal/blob/d46a0fe5e0b95bb2d6df2fa72540d54eb68a4959/models/gpt2/innerdetox_hook.py#L37,
and the others are handled by the register_forward_hook.

**Comment by a101269** [comment]
> Hi, the parameters for the read_hook are `def read_hook(self, module, input, output, module_name=None, prompt_end_indices=None)`, where the module, input, and output are passed by the Pytorch's register_forward_hook function (https://pytorch.org/docs/stable/generated/torch.nn.modules.module.register_module_forward_hook.html),
> 
> and the module_name and prompt_end_indices are passed via a partial function at
> 
> https://github.com/cooperleong00/ToxificationReversal/blob/d46a0fe5e0b95bb2d6df2fa72540d54eb68a4959/scripts/run_generation.py#L107
> 
> Likewise, the parameter module_name of the write_hook is passed at
> 
> https://github.com/cooperleong00/ToxificationReversal/blob/d46a0fe5e0b95bb2d6df2fa72540d54eb68a4959/models/gpt2/innerdetox_hook.py#L37
> 
> ,
> and the others are handled by the register_forward_hook.

Understood, thank you for your response.
